---
- hosts: localhost
  connection: local
  gather_facts: False
  
  tasks:
  
    - name: Creating set of EC2 Instances
      ec2:
        group: sg-084eb47eea13c0020
        instance_type: t2.micro
        image: ami-03f0fd1a2ba530e75
        region: us-east-1
        wait: true
        exact_count: 1
        count_tag:
          Name: Demo
        instance_tags:
          Name: Demo
      register: ec2_info
        
  - debug:
      msg: "{{ec2_info}}"
