---
- name: Setup EC2
  hosts: localhost
  connection: local
  gather_facts: no
  vars_file:
    - vars/cloudvars
  tasks:
    - name: create ec2 key-pair
      ec2_key:
        name: ec2-key
        region: "{{region}}"
      register: ec2_key_info
      
#    - debug:
#        msg: "{{ec2_key_info}}"
        
    - name: Copy the private key
      copy:
        content: "{{ec2_key_info.key.private_key}}"
        dest: "./login_key.pem"
        mode: 0600
      when: ec2_key_info.changed
      
    - name: Create Security Group for ec2 Instance
      ec2_group:
        name: ec2-sg
        description: Allow port 22, 8080 and 3306
        region: "{{region}}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
            
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{myip}}"            
          
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: "{{myip}}"

          - proto: tcp
            from_port: 3306
            to_port: 3306
            cidr_ip: "{{myip}}"
            
      register: ec2_sg_info
      
    - name: Creating set of EC2 Instances
      ec2:
        key: ec2-key
        group: ec2-sg
        instance_type: t2.micro
        image: ami-03f0fd1a2ba530e75
        region: ap-south-1
        wait: true
        wait_timeout: 300
        exact_count: 1
        count_tag:
          Name: "{{item}}"
        instance_tags:
          Name: "{{item}}"
      with_items:
        - Nginx
        - Tomcat
        - db
      register: ec2_info
        
    - debug:
        msg: "{{ec2_info}}"
