---
- name: Setup Nginx svc
  hosts: localhost
  connection: local
  become: yes
  become_method: sudo
  task:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
        
    - name: Start & Enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes
