---
- name: Setup Nginx svc
  hosts: localhost
  connection: local
  become: yes
  become_method: sudo
  task:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
        
    - name: Start & Enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes
        
    - name: Disable Nginx default website
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
        
    - name: Deploy web config file
      template:
        src: templates/nginxvpro.j2
        dest: /etc/nginx/site-available/myapp

    -  name: Enable website
       file:
         src: /etc/nginx/site-available/myapp
         dest: /etc/nginx/site-enabled/myapp
         state: link
       notify:
         - Restart Nginx
         
handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
